Simplon-hdf/concepteur-developpeur.com

- NPM.md
Adding introduction to NPM in my doc, french only at this moment.
> docs(common): introducing NPM

- GIT.md
add new documentation GIT for introduction and installation
> docs(commons): add new documentation GIT for introduction and installation

- GIT.md
I add in document GIT :
- basic command
- working with image
- example create empty repository
> docs(common) add in document GIT basic command, working and example create empty repository

- GITFLOW.md
I added the gitflow.md file, containing the description and the installation of GitFlow.
> docs(common) add in document gitFlow description and installation

- Definition agilitymethod.md
>  doc(common) Add definition agility method

- GIT.md
Add definition of branch with an example and a image
> docs(common): add definition of branch with an example

- GIT.md
Definition pull request with image
> docs(common): add definition pull request with image

- GITFLOW.md
I added the part about gitflow feature.
> docs(common): add feature part

- package.json
Adding a package.json file example
> docs(common): adding package.json file

- jira-presentation.md
this is party speall of the introduction of tools jira
add introduction jira
> docs(jira): add the first party of the jira documentation

- agile-method.md
add description of the principlesagility method
> docs(common): add description of the principlesagility method

- GIT.md
> docs(common): add functioning pull request

- GITFLOW.md
I added the part about release and hotfix
> docs(common) : add release and hotfix part

- agile-method.md
add introduction to the agile method
> docs(common) : add introduction to the agile method

- README.md
- npm-en.md
Updating links in README.md.
Adaptation of texts of clickable links.
Correcting structural npm doc errors.
> fix(common): updating readme, update npm english version doc

- agile-method.md
last step the scrum add the definition
> docs(common): last step the scrum add the definition

- agile-method.md
> docs(common): i added a scrum image

- jira-presentation.md
add the section service management of jira software
service management
> docs(jira): add the doc of service management

- jira-presentation.md
> docs(common): add presentation jira

- .\
add the section work-management, jira-align, ect...
the end of the documentation for jira software
> docs(commons): add the end section of documentation for jira software

- .\
> fix(common): remove '.\' file

- README.md
- jira-presentation.md
- npm-fr.md
Table of content reworked.
Fix spell errors in jira-presentation.md.
FIx spell errors in npm-fr.md
> docs + fix(common + typo): table of content reworked : filled and organized; fix spell errors

- gitflow.md
I added images and a reference section
> docs(commons): add image and reference part

- .gitignore
- git.md
- npm-en.md
- npm-fr.md
- planningPoker.md
- velocite.md
Reverts Simplon-hdf/concepteur-developpeur.com#100
This Pull Request delete one part of git and table of content.
> Revert "fix(commons):typo minor correction on npm-en.md | npm-fr.md"
